version: 2
updates:

# Accessibility Specs /src-a11y"
  - package-ecosystem: "npm"
    directory: "/src-a11y"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@progress/wct-a11y-spec"
    commit-message:
      prefix: "chore:"