title: Wai-Aria Support
component: AIPrompt
from: /aria/ai-prompt_aria.md
dest: ../components/aiprompt/accessibility/wai-aria-support.md
slug: aiprompt-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug:accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor AIPrompt Demos](https://demos.telerik.com/blazor-ui/aiprompt/overview)
    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
