title: Wai-Aria Support
component: Breadcrumb
from: /aria/breadcrumb_aria.md
dest: ../components/breadcrumb/accessibility/wai-aria-support.md
slug: breadcrumb-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Breadcrumb keyboard navigation works, refer to the [Blazor Breadcrumb Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/breadcrumb/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
