title: Wai-Aria Support
component: Button
from: /aria/button_aria.md
dest: ../components/button/accessibility/wai-aria-support.md
slug: button-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Button keyboard navigation works, refer to the [Blazor Button Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/button/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
