title: Wai-Aria Support
component: Calendar
from: /aria/calendar_aria.md
dest: ../components/calendar/accessibility/wai-aria-support.md
slug: calendar-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Calendar keyboard navigation works, refer to the [Blazor Calendar Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/calendar/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
