title: Wai-Aria Support
component: ColorGradient
from: /aria/colorgradient_aria.md
dest: ../components/colorgradient/accessibility/wai-aria-support.md
slug: colorgradient-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the ColorGradient keyboard navigation works, refer to the [Blazor ColorGradient Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/colorgradient/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
