title: Wai-Aria Support
component: ColorPicker
from: /aria/colorpicker_aria.md
dest: ../components/colorpicker/accessibility/wai-aria-support.md
slug: colorpicker-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor ColorPicker Overview (Demo)](https://demos.telerik.com/blazor-ui/colorpicker/overview)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug themes-accessibility-swatch %})
