title: Wai-Aria Support
component: ColorPicker
from: /aria/colorpicker_aria.md
dest: ../components/colorpicker/accessibility/wai-aria-support.md
slug: colorpicker-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the ColorPicker keyboard navigation works, refer to:

    * [Blazor ColorGradient Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/colorgradient/keyboard-navigation)
    * [Blazor ColorPalette Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/colorpalette/keyboard-navigation)

    ## See Also

    * [Blazor ColorPicker Demos](https://demos.telerik.com/blazor-ui/colorpicker/overview)
    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
