title: Wai-Aria Support
component: ComboBox
from: /aria/combobox_aria.md
dest: ../components/combobox/accessibility/wai-aria-support.md
slug: combobox-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the ComboBox keyboard navigation works, refer to the [Blazor ComboBox Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/combobox/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
