title: Wai-Aria Support
component: ContextMenu
from: /aria/context-menu_aria.md
dest: ../components/contextmenu/accessibility/wai-aria-support.md
slug: contextmenu-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor ContextMenu Accessibility and Keyboard Navigation (Demo)](https://demos.telerik.com/blazor-ui/contextmenu/keyboard-navigation)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug themes-accessibility-swatch %})