title: Wai-Aria Support
component: DateTimePicker
from: /aria/datetimepicker_aria.md
dest: ../components/datetimepicker/accessibility/wai-aria-support.md
slug: datetimepicker-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the DateTimePicker keyboard navigation works, refer to the [Blazor DateTimePicker Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/datetimepicker/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
