title: Wai-Aria Support
component: DatePicker
from: /aria/datepicker_aria.md
dest: ../components/datepicker/accessibility/wai-aria-support.md
slug: datepicker-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the DatePicker keyboard navigation works, refer to the [Blazor DatePicker Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/datepicker/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
