title: Wai-Aria Support
component: Drawer
from: /aria/drawer_aria.md
dest: ../components/drawer/accessibility/wai-aria-support.md
slug: drawer-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Drawer keyboard navigation works, refer to the [Blazor Drawer Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/drawer/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
