title: Wai-Aria Support
component: DropDownList
from: /aria/dropdownlist_aria.md
dest: ../components/dropdownlist/accessibility/wai-aria-support.md
slug: dropdownlist-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor DropDownList Accessibility and Keyboard Navigation (Demo)](https://demos.telerik.com/blazor-ui/dropdownlist/keyboard-navigation)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug accessibility-swatch %})
