title: Wai-Aria Support
component: DropDownList
from: /aria/dropdownlist_aria.md
dest: ../components/dropdownlist/accessibility/wai-aria-support.md
slug: dropdownlist-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the DropDownList keyboard navigation works, refer to the [Blazor DropDownList Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/dropdownlist/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
