title: Wai-Aria Support
component: FileManager
from: /aria/filemanager_aria.md
dest: ../components/filemanager/accessibility/wai-aria-support.md
slug: filemanager-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug://accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor FileManager Demos](https://demos.telerik.com/blazor-ui/filemanager/overview)
    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
