title: Wai-Aria Support
component: Filter
from: /aria/filter_aria.md
dest: ../components/filter/accessibility/wai-aria-support.md
slug: filter-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Filter keyboard navigation works, refer to the [Blazor Filter Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/filter/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
