title: Wai-Aria Support
component: FlatColorPicker
from: /aria/flatcolorpicker_aria.md
dest: ../components/flatcolorpicker/accessibility/wai-aria-support.md
slug: flatcolorpicker-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the FlatColorPicker keyboard navigation works, refer to:

    * [Blazor ColorGradient Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/colorgradient/keyboard-navigation)
    * [Blazor ColorPalette Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/colorpalette/keyboard-navigation)

    ## See Also

    * [Blazor FlatColorPicker Demos](https://demos.telerik.com/blazor-ui/flatcolorpicker/overview)
    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
