title: Wai-Aria Support
component: FloatingActionButton
from: /aria/floatingactionbutton_aria.md
dest: ../components/floatingactionbutton/accessibility/wai-aria-support.md
slug: floatingactionbutton-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug://accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [FloatingActionButton Overview](https://demos.telerik.com/blazor-ui/floatingactionbutton/overview)
    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)