title: Wai-Aria Support
component: Gantt
from: /aria/gantt_aria.md
dest: ../components/gantt/accessibility/wai-aria-support.md
slug: gantt-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug://accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor Gantt Demos](https://demos.telerik.com/blazor-ui/gantt/overview)
    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
