title: Wai-Aria Support
component: Grid
from: /aria/grid_aria.md
dest: ../components/grid/accessibility/wai-aria-support.md
slug: grid-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Grid keyboard navigation works, refer to the [Blazor Grid Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/grid/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
