title: Wai-Aria Support
component: ListBox
from: /aria/listbox_aria.md
dest: ../components/listbox/accessibility/wai-aria-support.md
slug: listbox-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the ListBox keyboard navigation works, refer to the [Blazor ListBox Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/listbox/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
