title: Wai-Aria Support
component: ListView
from: /aria/listview_aria.md
dest: ../components/listview/accessibility/wai-aria-support.md
slug: listview-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug://accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor ListView Demos](https://demos.telerik.com/blazor-ui/listview/overview)
    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
