title: Wai-Aria Support
component: MaskedTextBox
from: /aria/maskedtextbox_aria.md
dest: ../components/maskedtextbox/accessibility/wai-aria-support.md
slug: maskedtextbox-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Live Demo: MaskedTextbox](https://demos.telerik.com/blazor-ui/maskedtextbox/overview)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug themes-accessibility-swatch %})
