title: Wai-Aria Support
component: Menu
from: /aria/menu_aria.md
dest: ../components/menu/accessibility/wai-aria-support.md
slug: menu-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Menu keyboard navigation works, refer to the [Blazor Menu Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/menu/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
