title: Wai-Aria Support
component: MultiSelect
from: /aria/multiselect_aria.md
dest: ../components/multiselect/accessibility/wai-aria-support.md
slug: multiselect-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the MultiSelect keyboard navigation works, refer to the [Blazor MultiSelect Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/multiselect/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
