title: Wai-Aria Support
component: Notification
from: /aria/notification_aria.md
dest: ../components/notification/accessibility/wai-aria-support.md
slug: notification-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview]({%slug accessibility-overview%}#keyboard-navigation) article.

    ## See Also

    * [Blazor Notification Demos](https://demos.telerik.com/blazor-ui/notification/overview)
    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
