title: Wai-Aria Support
component: NumericTextBox
from: /aria/numerictextbox_aria.md
dest: ../components/numerictextbox/accessibility/wai-aria-support.md
slug: numerictextbox-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the NumericTextBox keyboard navigation works, refer to the [Blazor NumericTextBox Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/numerictextbox/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
