title: Wai-Aria Support
component: Pager
from: /aria/pager_aria.md
dest: ../components/pager/accessibility/wai-aria-support.md
slug: pager-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Pager keyboard navigation works, refer to the [Blazor Pager Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/pager/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
