title: Wai-Aria Support
component: PanelBar
from: /aria/panelbar_aria.md
dest: ../components/panelbar/accessibility/wai-aria-support.md
slug: panelbar-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the PanelBar keyboard navigation works, refer to the [Blazor PanelBar Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/panelbar/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
