title: Wai-Aria Support
component: Popover
from: /aria/popover_aria.md
dest: ../components/popover/accessibility/wai-aria-support.md
slug: popover-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug://accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor Popover Demos](https://demos.telerik.com/blazor-ui/popover/overview)
    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
