title: Wai-Aria Support
component: RadioGroup
from: /aria/radiogroup_aria.md
dest: ../components/radiogroup/accessibility/wai-aria-support.md
slug: radiogroup-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the RadioGroup keyboard navigation works, refer to the [Blazor RadioGroup Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/radiogroup/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
