title: Wai-Aria Support
component: RangeSlider
from: /aria/range-slider_aria.md
dest: ../components/rangeslider/accessibility/wai-aria-support.md
slug: rangeslider-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the RangeSlider keyboard navigation works, refer to the [Blazor RangeSlider Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/rangeslider/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
