title: Wai-Aria Support
component: Rating
from: /aria/rating_aria.md
dest: ../components/rating/accessibility/wai-aria-support.md
slug: rating-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Rating keyboard navigation works, refer to the [Blazor Rating Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/rating/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
