title: Wai-Aria Support
component: Scheduler
from: /aria/scheduler_aria.md
dest: ../components/scheduler/accessibility/wai-aria-support.md
slug: scheduler-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Scheduler keyboard navigation works, refer to the [Blazor Scheduler Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/scheduler/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
