title: Wai-Aria Support
component: Signature
from: /aria/signature_aria.md
dest: ../components/signature/accessibility/wai-aria-support.md
slug: signature-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview](slug:accessibility-overview#keyboard-navigation) article.

    ## See Also

    * [Blazor Signature Demos](https://demos.telerik.com/blazor-ui/signature/overview)
    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
