title: Wai-Aria Support
component: SplitButton
from: /aria/splitbutton_aria.md
dest: ../components/splitbutton/accessibility/wai-aria-support.md
slug: splitbutton-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the SplitButton keyboard navigation works, refer to the [Blazor SplitButton Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/splitbutton/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
