title: Wai-Aria Support
component: Splitter
from: /aria/splitter_aria.md
dest: ../components/splitter/accessibility/wai-aria-support.md
slug: splitter-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Splitter keyboard navigation works, refer to the [Blazor Splitter Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/splitter/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
