title: Wai-Aria Support
component: Switch
from: /aria/switch_aria.md
dest: ../components/switch/accessibility/wai-aria-support.md
slug: switch-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor Switch Accessibility and Keyboard Navigation (Demo)](https://demos.telerik.com/blazor-ui/switch/keyboard-navigation)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug themes-accessibility-swatch %})