title: Wai-Aria Support
component: Switch
from: /aria/switch_aria.md
dest: ../components/switch/accessibility/wai-aria-support.md
slug: switch-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Switch keyboard navigation works, refer to the [Blazor Switch Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/switch/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug://accessibility-overview)
