title: Wai-Aria Support
component: TabStrip
from: /aria/tabstrip_aria.md
dest: ../components/tabstrip/accessibility/wai-aria-support.md
slug: tabstrip-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the TabStrip keyboard navigation works, refer to the [Blazor TabStrip Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/tabstrip/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
