title: Wai-Aria Support
component: TileLayout
from: /aria/tilelayout_aria.md
dest: ../components/tilelayout/accessibility/wai-aria-support.md
slug: tilelayout-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the TileLayout keyboard navigation works, refer to the [Blazor TileLayout Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/tilelayout/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
