title: Wai-Aria Support
component: TileLayout
from: /aria/tilelayout_aria.md
dest: ../components/tilelayout/accessibility/wai-aria-support.md
slug: tilelayout-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview]({%slug accessibility-overview%}#keyboard-navigation) article.

    ## See Also

    * [Blazor TileLayout Demos](https://demos.telerik.com/blazor-ui/tilelayout/overview)
    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
