title: Wai-Aria Support
component: TimePicker
from: /aria/timepicker_aria.md
dest: ../components/timepicker/accessibility/wai-aria-support.md
slug: timepicker-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor TimePicker Accessibility and Keyboard Navigation (Demo)](https://demos.telerik.com/blazor-ui/timepicker/keyboard-navigation)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug accessibility-swatch %})
