title: Wai-Aria Support
component: ToggleButton
from: /aria/togglebutton_aria.md
dest: ../components/togglebutton/accessibility/wai-aria-support.md
slug: togglebutton-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor ToggleButton Accessibility and Keyboard Navigation (Demo)](https://demos.telerik.com/blazor-ui/togglebutton/keyboard-navigation)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug themes-accessibility-swatch %})
