title: Wai-Aria Support
component: Toolbar
from: /aria/toolbar_aria.md
dest: ../components/toolbar/accessibility/wai-aria-support.md
slug: toolbar-wai-aria-support
position: 50
after:  |
    ## See Also

    * [Blazor Toolbar Accessibility and Keyboard Navigation (Demo)](https://demos.telerik.com/blazor-ui/toolbar/keyboard-navigation)
    * [Accessibility in Telerik UI for Blazor]({% slug accessibility-overview %})
    * [Accessibility Theme]({% slug themes-accessibility-swatch %})