title: Wai-Aria Support
component: Tooltip
from: /aria/tooltip_aria.md
dest: ../components/tooltip/accessibility/wai-aria-support.md
slug: tooltip-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the keyboard navigation works in Telerik UI for Blazor, refer to the [Accessibility Overview]({%slug accessibility-overview%}#keyboard-navigation) article.

    ## See Also

    * [Blazor Tooltip Demos](https://demos.telerik.com/blazor-ui/tooltip/overview)
    * [Accessibility in Telerik UI for Blazor]({%slug accessibility-overview%})
