title: Wai-Aria Support
component: TreeList
from: /aria/treelist_aria.md
dest: ../components/treelist/accessibility/wai-aria-support.md
slug: treelist-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the TreeList keyboard navigation works, refer to the [Blazor TreeList Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/treelist/keyboard-navigation).

    ## See Also

    * [Blazor TreeList Accessibility Example](slug:treelist-accessibility-overview#blazor-treelist-accessibility-example)
    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
