title: Wai-Aria Support
component: Wizard
from: /aria/wizard_aria.md
dest: ../components/wizard/accessibility/wai-aria-support.md
slug: wizard-wai-aria-support
position: 50
after:  |
    ## Keyboard Navigation

    For details on how the Wizard keyboard navigation works, refer to the [Blazor Wizard Accessibility and Keyboard Navigation Demo](https://demos.telerik.com/blazor-ui/wizard/keyboard-navigation).

    ## See Also

    * [Accessibility in Telerik UI for Blazor](slug:accessibility-overview)
