name: Docs No API

on:
  workflow_call:

permissions:
    id-token: write # Required by Akeyless
    contents: read
    packages: read

jobs:
  build_docs_no_api:
    runs-on: ubuntu-latest
    env:
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

    container:
      image: ghcr.io/telerik/blazor-build:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ github.token }}
      options: --user 1001 --cap-add=SYS_ADMIN --shm-size="4g"

    defaults:
      run:
        # Use a login Bash shell to enable RVM
        shell: bash -leo pipefail {0}

    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: '{ "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN" }'
          export-secrets-to-environment: false

      - name: Clone Blazor-Docs Repository
        uses: actions/checkout@v3
        with:
          path: temp/blazor-docs

      - name: Check out Docs-Seed repo
        uses: actions/checkout@v3
        with:
          repository: telerik/docs-seed
          path: temp/docs-seed
          ref: master
          token: ${{ steps.import-secrets.outputs.GH_TOKEN }}
          fetch-depth: "0"

      - name: Copy docs-seed elements
        run: |
          rsync -avc --exclude-from=./exclude.txt $(pwd)/ "../blazor-docs/"
        working-directory: temp/docs-seed

      - name: Build docs site with Jekyll
        env:
          RUBYOPT: -KU -E utf-8:utf-8
        run: |
          bundle --without development --path ~/gems
          bundle exec jekyll build --config=_config.yml,_test_iis.yml
        working-directory: temp/blazor-docs
