name: Docs Build

on:
  workflow_call:

permissions:
    id-token: write # Required by Akeyless
    contents: write
    packages: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required by Akeyless
      contents: write
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: LanceMcCarthy/akeyless-action@v3
        with:
          access-id: ${{ secrets.GH_AKEYLESS_ACCESS_ID }}
          static-secrets: |
            {
              "/WebComponents/prod/tokens/GH_TOKEN": "GH_TOKEN"
            }
          export-secrets-to-environment: false

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: gh auth login --with-token
          
      - name: Fetch Latest Successful Docs Deploy Run ID
        id: fetch_run
        run: |
          latest_run_id=$(gh run list --repo telerik/blazor --workflow docs-builder-manual.yml --json databaseId,status,conclusion --jq '.[] | select(.status == "completed" and .conclusion == "success") | .databaseId' | head -n 1)
          echo "Latest successful run ID: $latest_run_id"
          echo "latest_docs_deploy_run_id=$latest_run_id" >> $GITHUB_ENV
  
      - name: Download API Metadata
        uses: actions/download-artifact@v4.1.7
        with:
          name: metadata
          github-token: ${{ steps.import-secrets.outputs.GH_TOKEN }}
          repository: telerik/blazor
          run-id: ${{ steps.fetch_run.outputs.latest_docs_deploy_run_id }}
  
      - name: Extract API Metadata
        run: 7z x ./metadata/metadata.zip -ometadata

      - name: Checkout blazor-docs Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ steps.import-secrets.outputs.GH_TOKEN }}
          fetch-depth: "0"

      - name: Checkout docs-builder Repository
        uses: actions/checkout@v4
        with:
            repository: telerik/docs-builder
            ref: master
            path: docs-builder
            token: ${{ steps.import-secrets.outputs.GH_TOKEN }}

      - name: Install NPM Packages
        run: npm ci
        working-directory: docs-builder

      - name: Build Content
        run: npm run prod-build --docsPath=../blazor-docs --docfxFilesPath=../metadata
        working-directory: docs-builder
