name: Comment PR Procedures

on:
  pull_request:
    branches: [master]    
    types:
      - opened
      - labeled

jobs:
  post_comment_master:
    runs-on: ubuntu-latest
    steps:
      - name: Create branch comment      
        if: ${{ github.base_ref == 'master' && contains(join(github.event.pull_request.labels.*.name, ''), 'merge-to-production') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: | 
            Hello @${{github.actor}}, 

            Check the below option if you would like to automatically generate PR to production. The automation uses the branch for the cherry-pick, and then will delete the branch. Please, do not delete it manually.
            
            - [ ] create pr to production